disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ğ•„ğ•†ğ•Šğ•Š ğ•†ğ”¸ğ•‚ â„‚ğ•†ğ•„ğ•„ğ•†â„•ğ•Š"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "April 20 2025"
logo = "mossoak-logo_circle.png"
description = "Moss Oak Commons"
author = { name = "ğ•„ğ•†ğ•Šğ•Š ğ•†ğ”¸ğ•‚ â„‚ğ•†ğ•„ğ•„ğ•†â„•ğ•Š", email = "contact@mossoakcommons.diy", image = "mossoak-logo_circle.png", imageQuality = 96, headline = "1905 Alliance Rd.", bio = "Your friendly neighborhood infoshop", links = [ { email = "mailto:contact@mossoakcommons.diy" }, { youtube = "https://youtube.com/username" }, { instagram = "https://instagram.com/username" }, { bluesky = "https://bsky.app/profile/username" } ] }
secondaryLogo = "fern.png"
